name: EndersPlugin
version: 1.0
main: enderbyteprograms.mcplugins.EndersPlugin.EndersPluginMain
api-version: 1.19
commands:
  aliassay:
    description: Pretend to be a different player in chat
    usage: /aliassay <user> <message>
    permission: endersplugin.aliassay
  epplugindebug:
    description: Dump Enderbyte Programs Plugin data
    usage: /epplugindebug
    permission: endersplugin.admin
  survival:
    description: Change own gamemode to survival
    usage: /survival
    permission: endersplugin.gamemode
  kickeveryone:
    description: Kick everyone from the server
    usage: /kickeveryone <reason>
    permission: endersplugin.admin
  creative:
    description: Change own gamemode to creative
    usage: /creative
    permission: endersplugin.gamemode
  minecartme:
    description: Give a minecart
    usage: /minecartme
    permission: endersplugin.utility
  smite:
    description: SMITE A PLAYER WITH TH EPOWER OF ZEUS
    usage: /smite <Player>
    permission: endersplugin.extended
  lastseen:
    description: Check when a player is last online
    usage: /lastseen <Player>
    permission: endersplugin.basic
  lsentity:
    description: List entity counts in world
    usage: /lsentity
    permission: endersplugin.utility
  clearminecarts:
    description: Clear minecarts
    usage: /clearminecarts
    permission: endersplugin.extended
  censor:
    description: Add a word to the censored list
    usage: /censor <Word>
    permission: endersplugin.admin
  uncensor:
    description: Remove a word from the censored list
    usage: /uncensor <Word>
    permission: endersplugin.admin
  speedometer:
    description: Enable or Disable the speedometer
    usage: /speedometer
    permission: endersplugin.basic
  epplugininfo:
    description: Get some basic info about Ender's Plugin
    usage: /epplugininfo
    permission: endersplugin.basic
