name: EndersPlugin
version: 0.8
main: enderbyteprograms.mcplugins.EndersPlugin.LastSeen
api-version: 1.19
commands:
  aliassay:
    description: Pretend to be a different player in chat
    usage: /aliassay <user> <message>
    permission: lastseen.aliassay
  epplugindebug:
    description: Dump Enderbyte Programs Plugin data
    usage: /epplugindebug
    permission: lastseen.dumpdata
  survival:
    description: Change own gamemode to survival
    usage: /survival
    permission: lastseen.gamemode
  kickeveryone:
    description: Kick everyone from the server
    usage: /kickeveryone <reason>
    permission: lastseen.kick
  creative:
    description: Change own gamemode to creative
    usage: /creative
    permission: lastseen.gamemode
  minecartme:
    description: Give a minecart
    usage: /minecartme
    permission: lastseen.minecart
  smite:
    description: SMITE A PLAYER WITH TH EPOWER OF ZEUS
    usage: /smite <Player>
    permission: lastseen.smite
  lastseen:
    description: Check when a player is last online
    usage: /lastseen <Player>
    permission: lastseen.lastseen
  lsentity:
    description: List entity counts in world
    usage: /lsentity
    permission: lastseen.lsentity
  clearminecarts:
    description: Clear minecarts
    usage: /clearminecarts
    permission: lastseen.clearmc
  censor:
    description: Add a word to the censored list
    usage: /censor <Word>
    permission: lastseen.censor
  uncensor:
    description: Remove a word from the censored list
    usage: /uncensor <Word>
    permission: lastseen.censor
  speedometer:
    description: Enable or Disable the speedometer
    usage: /speedometer
    permission: lastseen.speed
